name: 'Chromatic'

on:
  push:
    branches: ['master']
    paths: ['**.stories.mdx', '**.vue', '**.js', '**.ts', '**.css']

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action-next@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          exitZeroOnChanges: true
          build-script-name: storybook:build
        env:
          CHROMATIC_RETRIES: 5
